## GoogleDriveをマウントする。

In [2]:
import os
if os.name == 'nt':
    print('OS is Windows: PASS mount google drive')
    g_dir_work = '../colab/'
else:
    from google.colab import drive
    drive.mount('/content/drive')
    g_dir_work = '/content/drive/My Drive/colab/'

# check mount point
print('\n<< Display work dir >>')
for file in os.listdir(g_dir_work):
    print( 'file/dir : ', file)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

<< Display work dir >>
file/dir :  mylib
file/dir :  test.txt
file/dir :  data
file/dir :  template.ipynb
file/dir :  .ipynb_checkpoints
file/dir :  models
file/dir :  mnist_cams
file/dir :  mnist_pix2pix


In [3]:
import os
print(os.getcwd())

/content


## 内作Libraryパスを通す。

In [6]:
import sys, os
if os.name == 'nt':# windows
    lib_path='../colab/mylib'
else:
    print(os.getcwd())
    lib_path='/content/drive/My Drive/colab/mylib/'
sys.path.append(lib_path)

/content


In [7]:
# check lib path
import myfunc
myfunc.test()

myfunc.test


以上、テンプレート

---

### Keras Backend

Reference : https://keras.io/ja/backend/

In [8]:
from keras import backend as K

Using TensorFlow backend.


#### Placeholder

In [11]:
input1 = K.placeholder(shape=(2, 4, 5))
# 以下も動作します:
input2 = K.placeholder(shape=(None, 4, 5))
# 以下も動作します:
input3 = K.placeholder(ndim=3)

print(input1)
print(input2)
print(input3)

Tensor("Placeholder_6:0", shape=(2, 4, 5), dtype=float32)
Tensor("Placeholder_7:0", shape=(?, 4, 5), dtype=float32)
Tensor("Placeholder_8:0", shape=(?, ?, ?), dtype=float32)


#### Variable

In [12]:
import numpy as np
arr = np.random.random((3, 4, 5))
var1 = K.variable(value=arr)

# すべて0の変数:
var2 = K.zeros(shape=(3, 4, 5))
# すべて1の変数:
var3 = K.ones(shape=(3, 4, 5))

print('var1', var1)
print('var2', var2)
print('var3', var3)

var1 <tf.Variable 'Variable:0' shape=(3, 4, 5) dtype=float32_ref>
var2 <tf.Variable 'Variable_1:0' shape=(3, 4, 5) dtype=float32_ref>
var3 <tf.Variable 'Variable_2:0' shape=(3, 4, 5) dtype=float32_ref>


#### Tensorによるgraph構築

In [19]:
# Initializing Tensors with Random Numbers
b = K.random_uniform_variable(shape=(3, 4), low=0, high=1) # Uniform distribution
c = K.random_normal_variable(shape=(3, 4), mean=0, scale=1) # Gaussian distribution
d = K.random_normal_variable(shape=(3, 4), mean=0, scale=1)
print('b :', b)
print('c :', c)
print('d :', d)

# Tensor Arithmetic
a = b + c * K.abs(d)
w = K.dot(a, K.transpose(b))
x = K.sum(b, axis=1)
y = K.softmax(b)
z = K.concatenate([b, c], axis=-1)
print('a :', a)
print('w :', w)
print('x :', x)
print('y :', y)
print('z :', z)

print('\nK.get_value() ---------')
print('b\n', K.get_value(b))
print('c\n', K.get_value(c))
print('d\n', K.get_value(d))
print('a\n', K.get_value(a))
print('w\n', K.get_value(w))
print('x\n', K.get_value(x))
print('y\n', K.get_value(y))
print('z\n', K.get_value(z))

b : <tf.Variable 'Variable_21:0' shape=(3, 4) dtype=float32_ref>
c : <tf.Variable 'Variable_22:0' shape=(3, 4) dtype=float32_ref>
d : <tf.Variable 'Variable_23:0' shape=(3, 4) dtype=float32_ref>
a : Tensor("add_6:0", shape=(3, 4), dtype=float32)
w : Tensor("MatMul_6:0", shape=(3, 3), dtype=float32)
x : Tensor("Sum_6:0", shape=(3,), dtype=float32)
y : Tensor("Softmax_6:0", shape=(3, 4), dtype=float32)
z : Tensor("concat_6:0", shape=(3, 8), dtype=float32)

K.get_value() ---------
b
 [[0.88469744 0.22565341 0.6631266  0.31298947]
 [0.28042984 0.90431213 0.1111598  0.54388595]
 [0.69458914 0.46255338 0.9695338  0.65385103]]
c
 [[-0.22750126 -0.7096699  -0.4932043   0.75154376]
 [ 0.29245773 -0.6164328   0.4228188   0.5268298 ]
 [ 0.8334179   1.3553936  -0.25433323  0.34936407]]
d
 [[ 0.57511425 -0.07956079  1.40565    -1.0608922 ]
 [-0.3046782   0.44312328 -1.9873228  -0.5193985 ]
 [-0.7500019   1.2910016   0.0227371   0.6964235 ]]
a
 [[ 0.7538582   0.16919151 -0.03014606  1.1102965 ]
 [ 0

#### よく使う演算
https://www.mathgram.xyz/entry/keras/backend

In [0]:
A = np.asarray([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

B = np.asarray([
        [9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]
    ])
A = K.variable(A)
B = K.variable(B)

In [21]:
# A
K.get_value(A)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [24]:
# 行列和
K.get_value(A + B)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]], dtype=float32)

In [25]:
# 行列差
K.get_value(A - B)

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]], dtype=float32)

In [26]:
# 行列要素同士の積
K.get_value(A * B)

array([[ 9., 16., 21.],
       [24., 25., 24.],
       [21., 16.,  9.]], dtype=float32)

In [31]:
# 行列積
K.get_value( K.dot(A, B) )

array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]], dtype=float32)

In [30]:
# 行列要素同士の商
K.get_value(A / B)

array([[0.11111111, 0.25      , 0.42857143],
       [0.6666667 , 1.        , 1.5       ],
       [2.3333333 , 4.        , 9.        ]], dtype=float32)

In [23]:
# 定数の和
K.get_value(A + 1)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]], dtype=float32)

In [28]:
# 行列要素の和
K.get_value(K.sum(A))

45.0

In [29]:
# 行列要素の平均
K.get_value(K.mean(A))

5.0

In [32]:
# 行列のサイズ取得
K.int_shape(A)

(3, 3)

In [33]:
# 行列の要素数
K.count_params(A)

9

In [34]:
# 行列の次元数
K.ndim(A)

2

In [35]:
# 行列のreshape
K.get_value(K.reshape(A, (1,9)))

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float32)

In [36]:
# 行列要素のClip
K.get_value(K.clip(A, 2, 5))

array([[2., 2., 3.],
       [4., 5., 5.],
       [5., 5., 5.]], dtype=float32)

In [38]:
# 要素を逆順に並べる。PIL.Image(RGB)をcv画像(BGR)に変換する時によく使う
K.reverse(x, axes=-1)

<tf.Tensor 'ReverseV2_1:0' shape=(3,) dtype=float32>

In [39]:
# sliceが可能
K.get_value(A[:,1])

array([2., 5., 8.], dtype=float32)

#### Layer作成
以下は実行するとエラーが発生する。

In [0]:
from keras import backend as K
from keras.layers import Input, Dense

inputs = Input((10, ))
x = K.relu(inputs * 2 + 1)
x = Dense(64, activation='relu')(x)

Lambdaを使用する。

In [0]:
from keras import backend as K
from keras.layers import Input, Dense, Lambda
inputs = Input((10, ))
x = K.relu(Lambda(lambda x: x * 2 + 1)(inputs))
x = Dense(64, activation='relu')(x)

#### 活性関数
keras.layers.advanced_activationsモジュール

In [0]:
from keras.layers import LeakyReLU
x = LeakyReLU(alpha=0.3)(x)

#### loss関数作成
https://qiita.com/mokemokechicken/items/483099fead460dc3a6fa

In [0]:
# mea(mean square error)の実装 (batchごとにmea計算)
def generator_loss(y_true, y_pred):  # y_true's shape=(batch_size, row, col, ch)
    return K.mean(K.abs(y_pred - y_true), axis=[1, 2, 3])