よく見る参照リンク  
https://qiita.com/ak11/items/67118e11b756b0ee83a5

---

Jupyter Notebookを単体テストやマニュアル作成ツールとして使う  
https://qiita.com/pashango2/items/942e0d9cf10b9e6e96e1

---

### t-SNEをkerasで作成。
fit_generatorの使い方がよくわかる。  

Parametric t-SNEの理論とKerasによる実装
https://qiita.com/koshian2/items/7aab45dafbdbd959d8fc

### K.reshapeの動作

In [2]:
import numpy as np
import tensorflow as tf
try:
    import tensorflow.keras as keras
    from tensorflow.keras import backend as K
except:
    import keras
    from keras import backend as K

In [11]:
img = np.zeros((3,2,5,5,6))
for i in range(3):
    for j in range(2):
        for k in range(6):
            img[i,j,:,:, k] = i*6*2 +j*6 +k+1

In [12]:
print(img[0,0,0,0,:])
print(img[0,1,0,0,:])
print(img[1,0,0,0,:])
print(img[1,1,0,0,:])
print(img[2,0,0,0,:])
print(img[2,1,0,0,:])

[1. 2. 3. 4. 5. 6.]
[ 7.  8.  9. 10. 11. 12.]
[13. 14. 15. 16. 17. 18.]
[19. 20. 21. 22. 23. 24.]
[25. 26. 27. 28. 29. 30.]
[31. 32. 33. 34. 35. 36.]


In [16]:
t_img  = K.variable(value=img)
t_msk  = K.variable(value=[0,1,1,1,1,1])
t_img2 = t_img * t_msk

In [17]:
v_img2 = K.get_value(t_img2)

In [18]:
print(v_img2[0,0,0,0,:])
print(v_img2[0,1,0,0,:])
print(v_img2[1,0,0,0,:])
print(v_img2[1,1,0,0,:])
print(v_img2[2,0,0,0,:])
print(v_img2[2,1,0,0,:])

[0. 2. 3. 4. 5. 6.]
[ 0.  8.  9. 10. 11. 12.]
[ 0. 14. 15. 16. 17. 18.]
[ 0. 20. 21. 22. 23. 24.]
[ 0. 26. 27. 28. 29. 30.]
[ 0. 32. 33. 34. 35. 36.]


In [19]:
t_img3 = K.reshape( t_img, (6,5,5,6) )
t_img4 = t_img * t_msk
v_img4 = K.get_value(t_img4)

print(v_img4[0,0,0,0,:])
print(v_img4[0,1,0,0,:])
print(v_img4[1,0,0,0,:])
print(v_img4[1,1,0,0,:])
print(v_img4[2,0,0,0,:])
print(v_img4[2,1,0,0,:])

[0. 2. 3. 4. 5. 6.]
[ 0.  8.  9. 10. 11. 12.]
[ 0. 14. 15. 16. 17. 18.]
[ 0. 20. 21. 22. 23. 24.]
[ 0. 26. 27. 28. 29. 30.]
[ 0. 32. 33. 34. 35. 36.]
